import { generateAugmentedRetrieval } from "@/utils/chat";
import { GoogleGenAI, Type } from "@google/genai";
import { NextRequest, NextResponse } from "next/server";

const apiKey=process.env.GOOGLE_GEMINI_API_KEY;
const embeddingModel=process.env.GOOGLE_EMBEDDING_MODEL;
const llmModel=process.env.GOOGLE_LLM_MODEL;

export async function POST(request:NextRequest){
    try {
        const ai = new GoogleGenAI({
            apiKey:apiKey
        });
        const message = await request.json();
        const embedding = await ai.models.embedContent({
            model:embeddingModel!,
            contents:message
        });
        if (!embedding.embeddings) {
            return NextResponse.json(
                { error: "Google embedding doesnt work" } , { status:500 }
            )
        }
        const rag = generateAugmentedRetrieval(message,embedding.embeddings[0].values ?? []);
        const model = ai.chats.create({
            model:llmModel!,
            config:{
                thinkingConfig:{
                    includeThoughts:true
                },
                responseMimeType:"application/json",
                responseSchema: {
                    type: Type.OBJECT,
                    required: ["message"],
                    properties: {
                        message: {
                            type: Type.STRING,
                            description: "Brief summary / short summarized answer to the user's question regarding my portfolio. This is the only response and this will also get rendered to the user interface (e.g. Zach Estrella has experience in ....)"
                        }
                    }
                }, 
                systemInstruction: [{
                    text:`
                        Role: You are a chatbot interpreter of my portfolio/personal information 
                        (I will send the data and score corresponding to me with embedded score generated via 
                        cosine similarity with embedded values generated by google gemini embedding)
                        Process: This process is RAG and this process is the last step wherein the LLM (you) will
                        interpret the data sent (computed by google gemini embedding and sorted by me via cosine similarity)
                        
                        OPERATIONAL PROTOCOL:
                        1. INPUT
                        - I will input the question of the user (in text form) together with chunks of information with their respective
                        generated score via cosine similarity. 

                        2. GENERATED SCORE VIA COSINE SIMILARITY
                        - Take note of the score, if the score of a chunk is below 0.5. Do not include it as your reference

                        3. INTERPRETATION
                        - If the user question does not have any relation (from your own interpretation and comparison and considering the score)
                        You can return or answer 'The information does not exist' (especially if the question not related to me)

                        4. OUTPUT
                        - Return a friendly UI message (without history) so its more of 1:1 convo to the user. Also make sure that the output is 
                        short but brief. From the information that I will provide, just summarize or answer directly (max is 1 paragraph).

                        5. IRRELEVANT QUESTION
                        - Even if the question is irrelevant, I will still send the request together with my general info. In case if there is zero
                        relevance of question in the data or the question is not asking any information related to me (e.g. Can you solve this etc..).
                        Return 'The question is not related to Zach Estrella or his portfolio' something like that.
                    `
                }]
            },
        });
        const response = await model.sendMessage({message:rag});
        const parsedResponse = JSON.parse(response.text as string)
        return NextResponse.json(
            {
                message: parsedResponse.message
            }, { status:200 }
        );
    } catch (error) {
        console.error(error);
        return NextResponse.json(
            {
                error: "Google model doesnt work",
                details: error instanceof Error ? error.message : "Google model doesnt work"
            }, { status:500 }
        )
    }
}